export const REMOVE_ERROR = 'REMOVE_ERROR'
export const REMOVE_LOADING = 'REMOVE_LOADING'
export const ADD_ERROR = 'ADD_ERROR'
export const ADD_LOADING = 'ADD_LOADING'

export const SET_USER = 'SET_USER'
export const SET_ISSUES = 'SET_ISSUES'
export const SET_LABELS = 'SET_LABELS'
export const SET_CURRENT_ISSUE = 'SET_CURRENT_ISSUE'
export const SET_REPO = 'SET_REPO'
export const SET_COMMENTS = 'SET_COMMENTS'
